"""tablas

Revision ID: 193f1a2d22d7
Revises: 
Create Date: 2023-07-15 15:43:26.356153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '193f1a2d22d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('apellido', sa.Text(), nullable=False),
    sa.Column('tipo_usuario', sa.Enum('ADMINISTRADOR', 'ESPECTADOR', 'EMPRESARIO', name='tipousuario'), nullable=False),
    sa.Column('correo', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('establecimientos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_establecimiento', sa.Enum('DISCOTECA', 'BAR', name='tipoestablecimiento'), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('distrito', sa.Text(), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=False),
    sa.Column('horario_lunes', sa.Text(), nullable=True),
    sa.Column('horario_martes', sa.Text(), nullable=True),
    sa.Column('horario_miercoles', sa.Text(), nullable=True),
    sa.Column('horario_jueves', sa.Text(), nullable=True),
    sa.Column('horario_viernes', sa.Text(), nullable=True),
    sa.Column('horario_sabado', sa.Text(), nullable=True),
    sa.Column('horario_domingo', sa.Text(), nullable=True),
    sa.Column('foto_logo', sa.Text(), nullable=False),
    sa.Column('foto_local_1', sa.Text(), nullable=True),
    sa.Column('foto_local_2', sa.Text(), nullable=True),
    sa.Column('foto_local_3', sa.Text(), nullable=True),
    sa.Column('foto_local_4', sa.Text(), nullable=True),
    sa.Column('pagina_web', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('foto_evento', sa.Text(), nullable=False),
    sa.Column('pagina_web', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eventos')
    op.drop_table('establecimientos')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
