"""creación de tablas

Revision ID: 193f1a2d22d7
Revises: 
Create Date: 2023-07-31 22:37:01.872954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '193f1a2d22d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventosE',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('foto_evento', sa.Text(), nullable=False),
    sa.Column('pagina_web', sa.Text(), nullable=True),
    sa.Column('establecimiento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['establecimiento_id'], ['establecimientos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eventosE')
    # ### end Alembic commands ###
